# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Luna ©
tagline:             'My Coding Journey'
description:         'My name is Chris Cahill. This blog traces my journey of becoming a software developer. Find me on <a href="https://github.com/luna-c" target="_blank">Github</a>. 
Thanks to <a href="https://twitter.com/mdo" target="_blank">@mdo</a> for building this jekyll theme.'
url:                 http://luna-c.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Chris Cahill
  url:               https://twitter.com/chr_stopherc
  email:             christopher.g.cahill@gmail.com

# Custom vars
version:             1.0.0
