# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Luna - C
tagline:             'My Coding Journey'
description:         'A blog to trace my becoming a software developer. Find me on <a href="https://github.com/luna-c" target="_blank">github</a>. Thanks to <a href="https://twitter.com/mdo" target="_blank">@mdo</a> for building this jekyll website.'
url:                 http://luna-c.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Chris Cahill
  url:               https://twitter.com/chr_stopherc
  email:             christopher.g.cahill@gmail.com

# Custom vars
version:             1.0.0
